### ISSUE TITLE
Preprocessor failes to validate wacz Files

### ISSUE THREAD

**Issue by YurkoWasHere** [starlinglab/integrity-preprocessor#44]
Error occurs 
` AttributeError: module 'validate' has no attribute 'Wacz'`

https://github.com/starlinglab/integrity-preprocessor/blob/dev/lib/common/__init__.py#L102

Note: When commented process continues

Oct  3 18:54:59 org2 python3[936029]: 2022-10-03 18:54:59 INFO Recorder Metadata Change Detected
Oct  3 18:54:59 org2 python3[936029]: Traceback (most recent call last):
Oct  3 18:54:59 org2 python3[936029]:   File "/root/integrity-preprocessor/browsertrix/main.py", line 434, in <module>
Oct  3 18:54:59 org2 python3[936029]:     meta_extra = common.parse_wacz_data_extra(wacz_path)
Oct  3 18:54:59 org2 python3[936029]:   File "/root/integrity-preprocessor/browsertrix/../lib/common/__init__.py", line 102, in parse_wacz_data_extra
Oct  3 18:54:59 org2 python3[936029]:     if not validate.Wacz(wacz_path).validate():
Oct  3 18:54:59 org2 python3[936029]: AttributeError: module 'validate' has no attribute 'Wacz'
Oct  3 18:54:59 org2 systemd[1]: integrity-preprocessor-browsertrix.service: Main process exited, code=exited, status=1/FAILURE
Oct  3 18:54:59 org2 systemd[1]: integrity-preprocessor-browsertrix.service: Failed with result 'exit-code'

**Comment by makeworld-the-better-one** [comment]
This has been fixed for now, a broader fix is in #48
